### ISSUE TITLE
Windows 11启动报错

### ISSUE THREAD

**Issue by MononeV** [nuthx/subtitle-renamer#7]
![image](https://github.com/nuthx/subtitle-renamer/assets/39477101/d1cf663f-06a1-41c9-96b0-726517eb6681)

Traceback (most recent call last):
  File "configparser.py", line 791, in get
  File "collections\__init__.py", line 986, in __getitem__
  File "collections\__init__.py", line 978, in __missing__
KeyError: 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 17, in <module>
  File "src\core.py", line 22, in __init__
  File "src\core.py", line 33, in initUI
  File "src\module\config.py", line 80, in readConfig
  File "src\module\config.py", line 62, in checkConfig
  File "configparser.py", line 794, in get
configparser.NoOptionError: No option 'encode' in section: 'General'

**Comment by nuthx** [comment]
新版修改了配置文件的内容，可能漏掉了部分配置的检查
打开我的电脑，地址栏中输入`%APPDATA%`，找到`SubtitleRenamer`文件夹，删除`config.ini`文件，再启动试试看

**Comment by nuthx** [comment]
如果还没删除，麻烦把`config.ini`的内容贴一下，我看看你的配置是什么状态
应该都改好了呀

**Comment by MononeV** [comment]
![image](https://github.com/nuthx/subtitle-renamer/assets/39477101/305cfa98-afba-4373-948b-63491b6c1f99)
Traceback (most recent call last):
  File "main.py", line 17, in <module>
  File "src\core.py", line 22, in __init__
  File "src\core.py", line 33, in initUI
  File "src\module\config.py", line 77, in readConfig
  File "src\module\config.py", line 51, in initConfig
  File "configparser.py", line 924, in write
  File "configparser.py", line 937, in _write_section
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 9-11: character maps to <undefined>

**Comment by MononeV** [comment]
> 如果还没删除，麻烦把`config.ini`的内容贴一下，我看看你的配置是什么状态 应该都改好了呀

这个报错是从v1.2.3开始的

**Comment by MononeV** [comment]
> 如果还没删除，麻烦把`config.ini`的内容贴一下，我看看你的配置是什么状态 应该都改好了呀

这个报错是从v1.2.3开始的

**Comment by nuthx** [comment]
尝试手动修改一下`config.ini`的内容并保存：
```
[Application]
version = 1.2

[Extension]
sc = 
tc = 

[General]
move_to_anime_folder = true
remove_unused_sub = true
encode = UTF-8

[Counter]
open_times = 0
rename_times = 0
rename_num = 0
```
是否能启动软件？
另外，你的操作系统是简体中文吗

**Comment by MononeV** [comment]
`[Application]
version = 1.2

[Extension]
sc = 
tc = 

[General]
move_to_anime_folder = true
remove_unused_sub = true

`
这个是之前删掉后启动软件自动生成的，加上后面的内容后可以正常启动了。我是英文系统。

**Comment by nuthx** [comment]
是UTF-8编码的问题，之前没考虑到配置中出现中文会报错
1.3.1及以前版本，不要在设置中把`转换字幕编码`改为`不转换`
稍后我更新1.3.2来修复

**Comment by nuthx** [comment]
@MononeV 
试一下这个版本是否能行
https://github.com/nuthx/subtitle-renamer/releases/download/1.3.2/SubtitleRenamer_windows.zip

**Comment by MononeV** [comment]
> 是UTF-8编码的问题，之前没考虑到配置中出现中文会报错
> 1.3.1及以前版本，不要在设置中把`转换字幕编码`改为`不转换`
> 稍后我更新1.3.2来修复

其实之前我没有改过设置。我从1.1开始用，1.1的设置打不开。1.3.2稍后我试一下。

**Comment by nuthx** [comment]
> > 是UTF-8编码的问题，之前没考虑到配置中出现中文会报错
> > 1.3.1及以前版本，不要在设置中把`转换字幕编码`改为`不转换`
> > 稍后我更新1.3.2来修复
> 
> 其实之前我没有改过设置。我从1.1开始用，1.1的设置打不开。1.3.2稍后我试一下。

1.2修改了配置内容，启动会有检测机制，如果是旧版的配置会强制更新
由于配置里出现了中文，所以非中文的操作系统会有编码问题
1.3.2移除了中文配置，并使用utf-8来写入配置文件
应该不会再报错了

**Comment by MononeV** [comment]
1.4启动报错
```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "src\core.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "src\gui\mainwindow.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "src\module\version.py", line 2, in <module>
ModuleNotFoundError: No module named 'requests'
```
